### ISSUE TITLE
Problem with Github public registry

### ISSUE THREAD

**Issue by gstolz** [ironpeakservices/iron-scratch#31]
Hi!
I know this is basically not a specific problem of this project, BUT...
Github public image registry currently[ does not support non-authenticated pull access](https://github.community/t/docker-pull-from-public-github-package-registry-fail-with-no-basic-auth-credentials-error/16358). This makes it hard to reference images in Dockerfiles. Since you already seem to maintain some images also on Docker Hub, I would like to ask, if you could update [this project on Docker Hub](https://hub.docker.com/r/ironpeakservices/go-scratch/dockerfile)
Thank you in advance!

**Comment by hazcod** [comment]
Hi @gstolz , you should be able to `docker pull ghcr.io/ironpeakservices/iron-scratch:1.0.1` now!
